# 该workflow的名称，可以随意填写
name: Build And Deploy To Github Pages

# workflow的触发事件，这里代表base分支的push事件触发
on:
  push:
    branches: [ base ]

# 任务
jobs:
  # build-and-deploy 为任务的ID
  build-and-deploy:
    # 运行所需要的环境
    runs-on: ubuntu-latest 

    steps:
      # 步骤名
      - name: Checkout
        # 使用的actions脚本，这里是官方提供的获取源码脚本
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        # 这个为使用 JamesIves/github-pages-deploy-action脚本所需要的配置
        with:
          persist-credentials: false
          node-version: 14.20.0

      # 执行npm脚本打包项目
      - name: Install and Build
        run: |
          npm install
          npm run build:h5
      
      # 执行JamesIves/github-pages-deploy-action将项目发布到Github Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 该workflow需要操作repo，因此需要一个密钥，这个密钥回调用环境变量，因为是个人密钥，会放在变量防止泄露
          token: ${{ secrets.GITHUB_TOKEN }}
          # 发布到的分支
          branch: web
          # 要发布的文件夹
          folder: dist/build/h5
